spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todoApplication
    username: banu
    password: banu@2804
  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect